### ISSUE TITLE
Support for contributing multiple projects to a single runtime

### ISSUE THREAD

**Issue by andrus** [nhl/bootique-cayenne#10]
Currently CayenneModule does not support loading multiple Cayenne configs into a single ServerRuntime. Add another YAML key to support that:

```
cayenne:
  config: c1.xml # this exists now
  configs: # new
    - c2.xml
    - c3.xml
```

Configs specified the new and the old way will be merged together.. And I guess we can deprecate "config" key and print a warning when it is found in the YAML
